#!/usr/bin/env python3
"""Generate Figure 1 (w(z) curves) and Figure 2 (systematic band) for LP32-S2."""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.interpolate import PchipInterpolator
import os

# Output directory
outdir = os.path.dirname(os.path.abspath(__file__))

# ============================================================
# Common settings
# ============================================================
plt.rcParams.update({
    'font.size': 11,
    'axes.labelsize': 13,
    'legend.fontsize': 10,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'text.usetex': False,
    'font.family': 'serif',
    'figure.dpi': 150,
})

# ============================================================
# DESI DR2 binned constraints
# ============================================================
desi_z  = np.array([0.25, 0.75, 1.25, 2.0])
desi_w  = np.array([-0.72, -0.95, -1.05, -0.90])
desi_dw = np.array([0.12, 0.15, 0.22, 0.35])

# ============================================================
# Model predictions at DESI bins (from SM Table 2)
# ============================================================
sfr_w  = np.array([-0.79, -0.88, -1.01, -0.90])
pcoll_w = np.array([-0.79, -0.91, -0.91, -0.80])

# ============================================================
# Figure 1: w(z) prediction curves
# ============================================================
fig, ax = plt.subplots(figsize=(7, 5))

# DESI data points with error bars
ax.errorbar(desi_z, desi_w, yerr=desi_dw, fmt='o', color='black',
            capsize=4, capthick=1.2, markersize=7, label='DESI DR2 (binned)')

# LambdaCDM
z_cont = np.linspace(0, 2.5, 200)
ax.plot(z_cont, -1 * np.ones_like(z_cont), 'k--', linewidth=1.2, alpha=0.5,
        label=r'$\Lambda$CDM ($w=-1$)')

# SFR driver -- create smooth curve through known DESI bin points
# Model values at DESI bins: z=0.25->-0.79, z=0.75->-0.88, z=1.25->-1.01, z=2.0->-0.90
# Plus z=0 matched to w0 calibration: z=0->-0.79
sfr_z_nodes = np.array([0, 0.25, 0.75, 1.25, 2.0])
sfr_w_nodes = np.array([-0.79, -0.79, -0.88, -1.01, -0.90])
sfr_smooth = PchipInterpolator(sfr_z_nodes, sfr_w_nodes)
sfr_w_cont = sfr_smooth(z_cont)
ax.plot(z_cont, sfr_w_cont, 'b-', linewidth=1.8, label='This work (SFR driver)')

# P_coll driver -- smooth curve through known DESI bin points
# Model values: z=0.25->-0.79, z=0.75->-0.91, z=1.25->-0.91, z=2.0->-0.80
# Plus z=0 matched to w0 calibration: z=0->-0.79
pcoll_z_nodes = np.array([0, 0.25, 0.75, 1.25, 2.0])
pcoll_w_nodes = np.array([-0.79, -0.79, -0.91, -0.91, -0.80])
pcoll_smooth = PchipInterpolator(pcoll_z_nodes, pcoll_w_nodes)
pcoll_w_cont = pcoll_smooth(z_cont)
ax.plot(z_cont, pcoll_w_cont, 'r-', linewidth=1.8, label=r'This work ($\mathcal{P}_{\rm coll}$ driver)')

# Phantom divide line
ax.axhline(y=-1, color='gray', linestyle=':', linewidth=0.8, alpha=0.6)
ax.text(2.55, -1.01, r'$w=-1$', fontsize=9, color='gray', va='top')

# Annotations
ax.annotate('Phantom crossing\n(SFR driver)', xy=(1.15, -1.01), xytext=(0.3, -1.10),
            arrowprops=dict(arrowstyle='->', color='blue', alpha=0.6),
            fontsize=9, color='blue')

ax.set_xlabel('Redshift $z$')
ax.set_ylabel('Dark energy EoS $w(z)$')
ax.set_xlim(0, 2.0)
ax.set_ylim(-1.20, -0.55)
ax.legend(loc='lower right', framealpha=0.9)
ax.grid(True, alpha=0.3)
ax.set_title('Figure 1: Predicted $w(z)$ vs. DESI DR2 binned constraints')

plt.tight_layout()
fig.savefig(os.path.join(outdir, 'fig_wz_prediction.pdf'), bbox_inches='tight')
fig.savefig(os.path.join(outdir, 'fig_wz_prediction.png'), bbox_inches='tight', dpi=200)
plt.close()
print("Figure 1 saved.")

# ============================================================
# Figure 2: Systematic uncertainty band (P_coll driver)
# ============================================================
fig, ax = plt.subplots(figsize=(7, 5))

# DESI data
ax.errorbar(desi_z, desi_w, yerr=desi_dw, fmt='o', color='black',
            capsize=4, capthick=1.2, markersize=7, label='DESI DR2 (binned)')

# LambdaCDM
ax.plot(z_cont, -1 * np.ones_like(z_cont), 'k--', linewidth=1.2, alpha=0.5,
        label=r'$\Lambda$CDM ($w=-1$)')

# Central P_coll prediction (Sheth-Tormen)
ax.plot(z_cont, pcoll_w_cont, 'r-', linewidth=1.8, label=r'$\mathcal{P}_{\rm coll}$ (Sheth--Tormen)')

# Illustrative envelope: generated by applying constant offsets (+0.08 / -0.12)
# that roughly bracket the range of published mass function and M_min variations
# (SM Table 1). This is an envelope, not a formal error band from MCMC propagation.
band_upper = pcoll_w_cont + 0.08
band_lower = pcoll_w_cont - 0.12
# Cap the band within plausible range
band_upper = np.minimum(band_upper, -0.75 + 0*z_cont)
band_lower = np.maximum(band_lower, -1.08 + 0*z_cont)

ax.fill_between(z_cont, band_lower, band_upper, alpha=0.25, color='red',
                label=r'Illustrative envelope (MF + $M_{\rm min}$ variation)')

# Phantom divide
ax.axhline(y=-1, color='gray', linestyle=':', linewidth=0.8, alpha=0.6)

ax.set_xlabel('Redshift $z$')
ax.set_ylabel('Dark energy EoS $w(z)$')
ax.set_xlim(0, 2.0)
ax.set_ylim(-1.20, -0.55)
ax.legend(loc='lower right', framealpha=0.9)
ax.grid(True, alpha=0.3)
ax.set_title(r'Figure 2: Illustrative envelope for $\mathcal{P}_{\rm coll}$ driver')

plt.tight_layout()
fig.savefig(os.path.join(outdir, 'fig_pcoll_band.pdf'), bbox_inches='tight')
fig.savefig(os.path.join(outdir, 'fig_pcoll_band.png'), bbox_inches='tight', dpi=200)
plt.close()
print("Figure 2 saved.")

print("All figures generated successfully.")
