"""LP23-R4 protocol-closure obstruction toy.

This script stress-tests the R3 failure mode.  R3 allowed an adversary to add
an arbitrary residual direction as a template/nuisance/history column, so any
finite residual could be absorbed.  R4 asks whether the same residual is still
absorbed when extension columns must be generated by an explicit protocol
grammar.

The constrained grammar below is intentionally a toy.  It is not a physical
law; it only models three physical-looking restrictions:

* locality: generated columns use nearest-neighbour edge stencils only;
* causality: response stencils point forward in a chosen protocol order;
* passivity/response: history kernels have decaying non-negative weights.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


TOL = 1e-9


@dataclass(frozen=True)
class ClosureResult:
    contract: str
    label: str
    rank: int
    residual_norm: float
    closedness: float
    column_closedness: float
    toy_limits: str


def incidence_matrix(nodes: int, edges: list[tuple[int, int]]) -> np.ndarray:
    d0 = np.zeros((len(edges), nodes), dtype=float)
    for row, (source, target) in enumerate(edges):
        d0[row, source] = -1.0
        d0[row, target] = 1.0
    return d0


def cycle_row(edge_count: int, signed_edges: list[tuple[int, float]]) -> np.ndarray:
    row = np.zeros(edge_count, dtype=float)
    for edge_index, sign in signed_edges:
        row[edge_index] = sign
    return row


def hstack(*blocks: np.ndarray) -> np.ndarray:
    nonempty = [b for b in blocks if b.size and b.shape[1] > 0]
    if nonempty:
        return np.column_stack(nonempty)
    rows = blocks[0].shape[0] if blocks else 0
    return np.zeros((rows, 0), dtype=float)


def matrix_rank(a: np.ndarray, tol: float = TOL) -> int:
    if a.size == 0:
        return 0
    return int(np.linalg.matrix_rank(a, tol=tol))


def whitened_project_residual(
    columns: np.ndarray,
    r: np.ndarray,
    sigma: np.ndarray,
    tol: float = TOL,
) -> tuple[int, float, np.ndarray]:
    rw = r / sigma
    if columns.size == 0 or columns.shape[1] == 0:
        return 0, float(np.linalg.norm(rw)), rw

    aw = columns / sigma[:, None]
    u, s, _ = np.linalg.svd(aw, full_matrices=False)
    rank = int(np.sum(s > tol))
    if rank == 0:
        return 0, float(np.linalg.norm(rw)), rw

    q = u[:, :rank]
    residual = rw - q @ (q.T @ rw)
    return rank, float(np.linalg.norm(residual)), residual


def unit_null_vector(constraints: np.ndarray, tol: float = TOL) -> np.ndarray:
    """Return one unit vector in the right null-space of constraints."""

    _, s, vh = np.linalg.svd(constraints, full_matrices=True)
    rank = int(np.sum(s > tol))
    candidate = vh[rank, :]
    norm = float(np.linalg.norm(candidate))
    if norm <= tol:
        raise ValueError("no null vector available")
    return candidate / norm


def vector(edge_count: int, entries: list[tuple[int, float]]) -> np.ndarray:
    out = np.zeros(edge_count, dtype=float)
    for index, value in entries:
        out[index] = value
    return out


def constrained_protocol_columns(edge_count: int) -> tuple[np.ndarray, list[str], str]:
    """Generate a deliberately finite local/causal/response toy grammar."""

    # e3,e4,e5 form an unfilled local loop.  The grammar allows a local loop
    # response but does not allow an oracle column pointing at the residual.
    local_loop = vector(edge_count, [(3, 1.0), (4, 1.0), (5, 1.0)])

    # Forward protocol histories with decaying weights.  These are artificial
    # FIR kernels: they encode the chosen order e6 -> e7 -> e8.
    history_fast = vector(edge_count, [(6, 1.0), (7, 0.45), (8, 0.20)])
    columns = np.column_stack([local_loop, history_fast])
    names = ["local_loop", "history_fast"]
    limits = (
        "toy-only: fixed graph, fixed protocol order, nearest-neighbour stencils, "
        "non-negative decaying FIR history kernels; not derived from Maxwell/EFT"
    )
    return columns, names, limits


def classify_contract(
    contract: str,
    d0: np.ndarray,
    d1: np.ndarray,
    sigma: np.ndarray,
    r: np.ndarray,
    extra_columns: np.ndarray,
    toy_limits: str,
    tol: float = TOL,
) -> ClosureResult:
    columns = hstack(d0, extra_columns)
    rank, residual_norm, _ = whitened_project_residual(columns, r, sigma, tol)
    closedness = float(np.linalg.norm(d1 @ r))
    if extra_columns.size and extra_columns.shape[1] > 0:
        column_closedness = float(np.max(np.linalg.norm(d1 @ extra_columns, axis=0)))
    else:
        column_closedness = 0.0

    if closedness > 1e-7:
        label = "UNDECIDED_NOT_CLOSED"
    elif residual_norm <= 1e-7:
        label = "OPEN_ABSORBED" if contract == "open_closure" else "CONSTRAINED_ABSORBED"
    else:
        label = "CONSTRAINED_OBSTRUCTION" if contract == "constrained_closure" else "OPEN_FAILED"

    return ClosureResult(
        contract=contract,
        label=label,
        rank=rank,
        residual_norm=residual_norm,
        closedness=closedness,
        column_closedness=column_closedness,
        toy_limits=toy_limits,
    )


def print_result(result: ClosureResult) -> None:
    print(
        f"{result.contract:22s} label={result.label:25s} "
        f"rank={result.rank:2d} closedness={result.closedness:.3g} "
        f"residual_norm={result.residual_norm:.10g} "
        f"column_closedness={result.column_closedness:.3g}"
    )
    print(f"  toy_limits={result.toy_limits}")


def run() -> None:
    nodes = 5
    edges = [
        (0, 1),  # e0
        (1, 2),  # e1
        (2, 0),  # e2: filled triangle, checked by D1
        (0, 2),  # e3
        (2, 3),  # e4
        (3, 0),  # e5: unfilled local loop
        (0, 3),  # e6
        (3, 4),  # e7
        (4, 0),  # e8: protocol-history loop sector
    ]
    d0 = incidence_matrix(nodes, edges)
    d1 = cycle_row(len(edges), [(0, 1.0), (1, 1.0), (2, 1.0)])[None, :]
    sigma = np.array([1.0, 1.3, 0.8, 1.2, 0.9, 1.1, 1.4, 0.95, 1.15], dtype=float)

    constrained_cols, names, constrained_limits = constrained_protocol_columns(len(edges))
    constrained_base = hstack(d0, constrained_cols)

    # The candidate residual is closed and outside the constrained grammar by
    # construction.  This is a pressure-test witness, not a physical residual.
    constraints = hstack(constrained_base).T
    constraints = np.vstack([constraints, d1])
    residual = unit_null_vector(constraints)

    open_cols = residual[:, None]
    open_limits = "open/oracle: arbitrary residual-direction column is allowed by definition"

    chain_error = float(np.linalg.norm(d1 @ d0))
    print("R4 protocol-closure obstruction toy")
    print(f"D0 shape={d0.shape} D1 shape={d1.shape} ||D1@D0||={chain_error:.3g}")
    print("")
    print("constrained generated columns:")
    for i, name in enumerate(names):
        print(
            f"  {name:16s} closedness={float(np.linalg.norm(d1 @ constrained_cols[:, i])):.3g} "
            f"support={np.nonzero(np.abs(constrained_cols[:, i]) > TOL)[0].tolist()}"
        )

    print("")
    print("candidate residual:")
    print(f"  closedness={float(np.linalg.norm(d1 @ residual)):.3g}")
    print(f"  residual={np.array2string(residual, precision=6, suppress_small=True)}")

    print("")
    print("closure comparison:")
    constrained = classify_contract(
        "constrained_closure",
        d0,
        d1,
        sigma,
        residual,
        constrained_cols,
        constrained_limits,
    )
    opened = classify_contract(
        "open_closure",
        d0,
        d1,
        sigma,
        residual,
        hstack(constrained_cols, open_cols),
        open_limits,
    )
    print_result(constrained)
    print_result(opened)

    print("")
    print("interpretation:")
    print("  open closure absorbs because the residual itself is admitted as a column.")
    print("  constrained closure leaves a non-zero class only relative to the toy grammar.")


if __name__ == "__main__":
    run()
